### PR TITLE
[automl] added multi-objective support

### PR DESCRIPTION
**Pull request by carolinepacheco**

### CODE REVIEW

**Comment by mboussaa** [comment]
@carolinepacheco I don't see how the "multi-objective support" algorithm is implemented in ur PR. Could you please tell me how can I check it? thx

**Review by Hiba-Alili — APPROVED** [review]

**Comment by andrewssobral** [comment]
> @carolinepacheco I don't see how the "multi-objective support" algorithm is implemented in ur PR. Could you please tell me how can I check it? thx

@mboussaa the algorithm exists already (MOCMAES - https://doc.activeeon.com/latest/PML/PMLUserGuide.html#_AutoML ), however the AutoML workflow not supported multi-objective functions. This is why Caroline modified it.

**Comment by mboussaa** [comment]
Thanks. Good to know.
Another question: is it worth making the "mu" parameter of MOCMAES configurable. It is now hardcoded "mu=2".

I read on internet: 
for mu – The number of parents used to generate the candidates. The higher this number is the better the Parato front coverage will be, but the longer it will take to converge.

What do you think @carolinepacheco @andrewssobral

**Comment by andrewssobral** [comment]
> Thanks. Good to know. Another question: is it worth making the "mu" parameter of MOCMAES configurable. It is now hardcoded "mu=2".
> 
> I read on internet: for mu – The number of parents used to generate the candidates. The higher this number is the better the Parato front coverage will be, but the longer it will take to converge.
> 
> What do you think @carolinepacheco @andrewssobral

Yes, I agree with you @mboussaa , but let's do it in another PR because it's a new feature, we should create some conditional workflow variables to address the internal parameters of each algorithm.

**Review by andrewssobral — APPROVED** [review]

**Pull request merged**
