### PR TITLE
add-signal_with_variable_interactive_control-workflow-and-refactor-wa…

### PR DESCRIPTION
**Pull request by oanaBiancaSchiopu**
…it_for_signal_with_variables

### CODE REVIEW

**Review by nebilbenmabrouk — APPROVED** [review]

**Review by AlexFalessi — APPROVED** [review]

**Comment by fviale** [comment]
Retest this please

**Comment by oanaBiancaSchiopu** [comment]
retest this please

**Comment by oanaBiancaSchiopu** [comment]
retest this please

**Comment by oanaBiancaSchiopu** [comment]
retest this please

**Comment by fviale** [comment]
add to whitelist

**Pull request merged**
