### PR TITLE
Fix is mac

### PR DESCRIPTION
**Pull request by mboussaa**

### CODE REVIEW

**Comment by mboussaa** [comment]
@andrewssobral Thank you for pointing out the issue. Could you review it?

**Comment by andrewssobral** [comment]
@mboussaa I think the best is to move out isWindows and isMac setting the default value as False, to avoid missing variable definition.

do this instead:
```
isWindows = false
isMac = false
switch (family) {
        case OperatingSystemFamily.WINDOWS:
            isWindows = true
            break
        case OperatingSystemFamily.MAC:
            isMac = true
            break
    }
```

Note: groovy scripts does not need `;` at the end of line

**Comment by mboussaa** [comment]
@andrewssobral done

**Review by andrewssobral — APPROVED** [review]

**Comment by andrewssobral** [comment]
LGTM! let's merge it ;-)

**Pull request merged**
