### PR TITLE
Fix Docker fork env for Mac OS

### PR DESCRIPTION
**Pull request by mboussaa**

### CODE REVIEW

**Review by fviale — APPROVED** [review]

**Review by andrewssobral — APPROVED** [review]

**Comment by mboussaa** [comment]
restest this please

**Comment by andrewssobral** [comment]
@mboussaa @fviale all AI workflows crashes after this PR:
Now I got:
```
Caused by: org.ow2.proactive.scripting.ScriptException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: isMac for class: Script20
```
Full logs in the attached file
[full.txt](https://github.com/ow2-proactive/proactive-examples/files/6423433/full.txt)

**Comment by andrewssobral** [comment]
@mboussaa @fviale this was my manual fix:
before:
```
switch (family) {
        case OperatingSystemFamily.WINDOWS:
            isWindows = true
            break
        case OperatingSystemFamily.MAC:
            isMac = true
        default:
            isWindows = false
    }
```

after:
```
switch (family) {
        case OperatingSystemFamily.WINDOWS:
            isWindows = true
            break
        case OperatingSystemFamily.MAC:
            isMac = true
            break
        default:
            isWindows = false
            isMac = false
    }
```

**Comment by mboussaa** [comment]
@andrewssobral Thank you for pointing out the issue and sorry for messing up with this. I have fixed in 2 new PRs if you can review and merge before the NR is triggered

**Comment by andrewssobral** [comment]
Yes sure thank you @mboussaa

**Pull request merged**
