### PR TITLE
Update post service start script with enableActions param

### PR DESCRIPTION
**Pull request by mklkun**

### CODE REVIEW

**Review by nebilbenmabrouk — APPROVED** [review]

**Review by fviale — APPROVED** [review]
LGTM
Just one thing, if you added a parameter to the script, did you search for all utilisations of this script ?
As args[0] when there is not argument will throw an exception.

**Comment by mklkun** [comment]
Yes. I created this script for PSA management workflows and these are all the workflows that are using it.

**Comment by fviale** [comment]
@mklkun but on saturday I tried to start a JupyterLab service from cloud automation and I had an error due to registerService missing parameter. So I am not sure these changes are sufficient.

**Comment by fviale** [comment]
The following search shows other uses:
https://github.com/ow2-proactive/proactive-examples/search?q=registerService

**Comment by mklkun** [comment]
I see that you are talking about the registerService while I was talking about the `Post_Service_Start.groovy` that I created for management workflows only. I will fix that for PSA services too.

**Comment by mklkun** [comment]
@fviale @mboussaa can one of you merge this PR please? Thanks in advance.

**Review by fviale — APPROVED** [review]

**Pull request merged**
